POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Testing",
  "author": "Test author",
  "url": "http://test.com"
}

###
PUT http://localhost:3003/api/blogs/65b3e7039e0186a8a06b7d9f
Content-Type: application/json

{
  "title": "Testing",
  "author": "Test author",
  "url": "http://test.com",
  "likes": 10
}

###
DELETE http://localhost:3003/api/blogs/65b3e5ceb3ea24d28bbe5305